version: 2

project_name: filebrowser

env:
  - GO111MODULE=on

builds:
  - env:
      - CGO_ENABLED=0
    main: main.go
    binary: filebrowser
    goos:
      - linux
    goarch:
      - amd64
    ignore: []

archives:
  - 
    name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    formats: [ 'tar.gz' ]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

dockers:
  - 
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "masterworgen/filebrowser:{{ .Tag }}-amd64"
      - "masterworgen/filebrowser:v{{ .Major }}-amd64"
    extra_files:
      - docker_config.json
      - healthcheck.sh

## s6 based docker images
  - 
    dockerfile: Dockerfile.s6
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "masterworgen/filebrowser:{{ .Tag }}-amd64-s6"
      - "masterworgen/filebrowser:v{{ .Major }}-amd64-s6"
    extra_files:
      - docker/root
      - healthcheck.sh

docker_manifests:
  - name_template: "masterworgen/filebrowser:latest"
    image_templates:
      - "masterworgen/filebrowser:{{ .Tag }}-amd64"
  - name_template: "masterworgen/filebrowser:{{ .Tag }}"
    image_templates:
      - "masterworgen/filebrowser:{{ .Tag }}-amd64"
  - name_template: "masterworgen/filebrowser:v{{ .Major }}"
    image_templates:
      - "masterworgen/filebrowser:v{{ .Major }}-amd64"
  - name_template: "masterworgen/filebrowser:s6"
    image_templates:
      - "masterworgen/filebrowser:{{ .Tag }}-amd64-s6"
  - name_template: "masterworgen/filebrowser:{{ .Tag }}-s6"
    image_templates:
      - "masterworgen/filebrowser:{{ .Tag }}-amd64-s6"
  - name_template: "masterworgen/filebrowser:v{{ .Major }}-s6"
    image_templates:
      - "masterworgen/filebrowser:v{{ .Major }}-amd64-s6"
