version: '3.8'

services:
  filebrowser:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config:/root/.config/filebrowser
    environment:
      - FB_DATABASE=/root/.config/filebrowser/filebrowser.db